extract = 'total_dyn_inst: (\d+)'
benchmarks = '../bril/benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.dce]
pipeline = [
    "bril2json",
    "cargo run -- -m dce",
    "brili -p {args}",
]

[runs.lvndce]
pipeline = [
    "bril2json",
    "cargo run -- -m lvn-dce",
    "brili -p {args}",
]

[runs.to-ssa]
pipeline = [
    "bril2json",
    "cargo run -- -m to-ssa",
    "brili -p {args}",
]

[runs.to-ssa-dce]
pipeline = [
    "bril2json",
    "cargo run -- -m to-ssa",
    "cargo run -- -m dce",
    "brili -p {args}",
]

[runs.to-ssa-and-back]
pipeline = [
    "bril2json",
    "cargo run -- -m to-ssa",
    "cargo run -- -m dce",
    "cargo run -- -m from-ssa",
    "brili -p {args}",
]
