extract = 'total_dyn_inst: (\d+)'
benchmarks = '../bril/benchmarks/core/*.bril'
[runs.to-ssa-dce]
pipeline = [
    "bril2json",
    "cargo run -- -m to-ssa",
    "cargo run -- -m dce",
    "brili -p {args}",
]

